language: node_js
node_js:
- '6.1'
- '6.0'
- '5.11'
- '5.0'
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/4a68bf119a287ae9d93b
    on_success: change
    on_failure: always
    on_start: never
