language: node_js
node_js:
- '5'
- '4'
- 'iojs'
- '0.12'
- '0.11'
- '0.10'
- '0.8'
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/4a68bf119a287ae9d93b
    on_success: change
    on_failure: always
    on_start: never
